import { Prompt } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import InstallBootstrap from "./utils/installBootstrap";


const prompt = Prompt({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">

      <body className={prompt.className}>
        {children}
        <InstallBootstrap />
      </body>
    </html>
  );
}